import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { getPurchaseOrderPdfUrl } from "@/api/purchase-orders";
import type { PurchaseOrder } from "../types";

interface PurchaseOrderPdfViewerProps {
  purchaseOrder: PurchaseOrder | null;
  onOpenChange: (open: boolean) => void;
}

export function PurchaseOrderPdfViewer({
  purchaseOrder,
  onOpenChange,
}: PurchaseOrderPdfViewerProps) {
  if (!purchaseOrder) return null;

  const pdfUrl = getPurchaseOrderPdfUrl(purchaseOrder.id);

  return (
    <Dialog open={!!purchaseOrder} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-4xl max-h-[95vh] flex flex-col p-0">
        <DialogHeader className="p-4 pb-2 shrink-0">
          <DialogTitle>Purchase Order PDF - {purchaseOrder.orderInfo.poNumber}</DialogTitle>
        </DialogHeader>

        <div className="flex-1 flex flex-col min-h-0 px-4 pb-4">
          <iframe
            src={pdfUrl}
            title={`Purchase Order ${purchaseOrder.orderInfo.poNumber}`}
            className="w-full flex-1 min-h-[500px] border border-slate-200 dark:border-white/10 rounded-lg bg-white dark:bg-slate-900"
          />
          <p className="text-[10px] text-slate-400 mt-2">
            PDF is generated by the backend. If you see a blank page, the backend may not be
            configured yet.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
