import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { getTaxTypePdfUrl } from "@/api/tax-types";
import type { TaxType } from "../types";

interface TaxTypePdfViewerProps {
  taxType: TaxType | null;
  onOpenChange: (open: boolean) => void;
}

export function TaxTypePdfViewer({ taxType, onOpenChange }: TaxTypePdfViewerProps) {
  if (!taxType) return null;

  const pdfUrl = getTaxTypePdfUrl(taxType.id);

  return (
    <Dialog open={!!taxType} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-4xl max-h-[95vh] flex flex-col p-0">
        <DialogHeader className="p-4 pb-2 shrink-0">
          <DialogTitle>Perpajakan PDF - {taxType.name}</DialogTitle>
        </DialogHeader>

        <div className="flex-1 flex flex-col min-h-0 px-4 pb-4">
          <iframe
            src={pdfUrl}
            title={`Tax Type ${taxType.name}`}
            className="w-full flex-1 min-h-[500px] border border-slate-200 dark:border-white/10 rounded-lg bg-white dark:bg-slate-900"
          />
          <p className="text-[10px] text-slate-400 mt-2">
            PDF is generated by the backend. If you see a blank page, the
            backend may not be configured yet.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
