import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { getTaxTypePdfUrl } from "@/api/tax-types";
import { usePdfBlobUrl } from "@/hooks/usePdfBlobUrl";
import type { TaxType } from "../types";
import { Loader2, AlertCircle } from "lucide-react";

interface TaxTypePdfViewerProps {
  taxType: TaxType | null;
  onOpenChange: (open: boolean) => void;
}

export function TaxTypePdfViewer({ taxType, onOpenChange }: TaxTypePdfViewerProps) {
  const apiUrl = taxType ? getTaxTypePdfUrl(taxType.id) : null;
  const { blobUrl, isLoading, error } = usePdfBlobUrl(apiUrl);

  if (!taxType) return null;

  return (
    <Dialog open={!!taxType} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-4xl max-h-[95vh] flex flex-col p-0">
        <DialogHeader className="p-4 pb-2 shrink-0">
          <DialogTitle>Perpajakan PDF - {taxType.name}</DialogTitle>
        </DialogHeader>

        <div className="flex-1 flex flex-col min-h-0 px-4 pb-4">
          {isLoading && (
            <div className="w-full flex-1 min-h-[500px] flex items-center justify-center border border-slate-200 dark:border-white/10 rounded-lg bg-slate-50 dark:bg-slate-900">
              <Loader2 className="h-8 w-8 animate-spin text-slate-400" />
            </div>
          )}
          {error && (
            <div className="w-full flex-1 min-h-[500px] flex flex-col items-center justify-center gap-2 border border-red-200 dark:border-red-800 rounded-lg bg-red-50 dark:bg-red-950/20 text-red-500">
              <AlertCircle className="h-8 w-8" />
              <p className="text-sm font-medium">Failed to load PDF</p>
              <p className="text-xs text-red-400">{error}</p>
            </div>
          )}
          {blobUrl && (
            <iframe
              src={blobUrl}
              title={`Tax Type ${taxType.name}`}
              className="w-full flex-1 min-h-[500px] border border-slate-200 dark:border-white/10 rounded-lg bg-white dark:bg-slate-900"
            />
          )}
          <p className="text-[10px] text-slate-400 mt-2">
            PDF is generated by the backend. If you see a blank page, the
            backend may not be configured yet.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
