import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { getBastPdfUrl } from "@/api/bast";
import type { BAST } from "../types";

interface BASTPdfViewerProps {
  bast: BAST | null;
  onOpenChange: (open: boolean) => void;
}

export function BASTPdfViewer({ bast, onOpenChange }: BASTPdfViewerProps) {
  if (!bast) return null;

  const pdfUrl = getBastPdfUrl(bast.id);

  return (
    <Dialog open={!!bast} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-4xl max-h-[95vh] flex flex-col p-0">
        <DialogHeader className="p-4 pb-2 shrink-0">
          <DialogTitle>BAST PDF - {bast.documentInfo.bastNumber}</DialogTitle>
        </DialogHeader>

        <div className="flex-1 flex flex-col min-h-0 px-4 pb-4">
          <iframe
            src={pdfUrl}
            title={`BAST ${bast.documentInfo.bastNumber}`}
            className="w-full flex-1 min-h-[500px] border border-slate-200 dark:border-white/10 rounded-lg bg-white dark:bg-slate-900"
          />
          <p className="text-[10px] text-slate-400 mt-2">
            PDF is generated by the backend. If you see a blank page, the
            backend may not be configured yet.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
