import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { getProposalPdfUrl } from "@/api/proposal-penawaran";
import type { ProposalPenawaran } from "../types";

interface ProposalPenawaranPdfViewerProps {
  proposal: ProposalPenawaran | null;
  onOpenChange: (open: boolean) => void;
}

export function ProposalPenawaranPdfViewer({
  proposal,
  onOpenChange,
}: ProposalPenawaranPdfViewerProps) {
  if (!proposal) return null;

  const pdfUrl = getProposalPdfUrl(proposal.id);

  return (
    <Dialog open={!!proposal} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-4xl max-h-[95vh] flex flex-col p-0">
        <DialogHeader className="p-4 pb-2 shrink-0">
          <DialogTitle>Proposal PDF - {proposal.proposalNumber}</DialogTitle>
        </DialogHeader>

        <div className="flex-1 flex flex-col min-h-0 px-4 pb-4">
          <iframe
            src={pdfUrl}
            title={`Proposal ${proposal.proposalNumber}`}
            className="w-full flex-1 min-h-[500px] border border-slate-200 dark:border-white/10 rounded-lg bg-white dark:bg-slate-900"
          />
          <p className="text-[10px] text-slate-400 mt-2">
            PDF is generated by the backend. If you see a blank page, the
            backend may not be configured yet.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
