import type { Client } from "./types";

export const mockClients: Client[] = [
  {
    id: "C001",
    name: "PT Bank Mandiri",
    companyName: "PT Bank Mandiri",
    address: "Jl. Jend. Gatot Subroto Kav. 36-38",
    phone: "021-5245879",
    email: "corporate@bankmandiri.co.id",
    npwp: "01.234.567.8-901.000",
    pic: { name: "Budi Santoso", position: "Manager", contact: "08123456789" },
    isActive: true,
  },
  {
    id: "C002",
    name: "PT Pertamina",
    companyName: "PT Pertamina (Persero)",
    address: "Jl. Medan Merdeka Timur 1A",
    phone: "021-500000",
    email: "info@pertamina.com",
    npwp: "01.234.567.8-902.000",
    pic: { name: "Ani Wijaya", position: "Procurement", contact: "08234567890" },
    isActive: true,
  },
  {
    id: "C003",
    name: "PT Telkomsel",
    companyName: "PT Telekomunikasi Seluler",
    address: "Gedung Telkomsel",
    phone: "021-1234567",
    email: "corporate@telkomsel.co.id",
    pic: { name: "Citra Dewi", position: "Project Lead", contact: "08345678901" },
    isActive: true,
  },
  {
    id: "C004",
    name: "Toyota Astra",
    companyName: "PT Toyota Astra Motor",
    address: "Jl. Yos Sudarso",
    phone: "021-6530000",
    email: "info@toyota.co.id",
    isActive: true,
  },
  {
    id: "C005",
    name: "Unilever Indonesia",
    companyName: "PT Unilever Indonesia Tbk",
    address: "Jl. Jend. Gatot Subroto",
    phone: "021-5299900",
    email: "corporate@unilever.com",
    isActive: true,
  },
];
